### ISSUE TITLE
Fix build due to dependency not compatible with node 0.8

### ISSUE THREAD

**Issue by lucasfcosta** [chaijs/pathval#23]
Apparently, due to [type-detect](https://github.com/chaijs/type-detect) not being compatible with Node 0.8, [this build is failing](https://travis-ci.org/chaijs/pathval/jobs/153991040#L205) and therefore we cannot release this properly with Semantic Release.

What should we do here, drop tests with Node 0.8 or start an effort to see if we can make type-detect run on that platform? What do you guys think it's better?

I need that in order to complete the change in Chai's core to make it use this external module instead of it's own utility module.

**Comment by keithamus** [comment]
Hmm, Node 0.8 is no longer officially supported, and as of October 1st Node 0.10 will no longer be supported either. I think we should probably support the longest lifecycles that Node supports, across all of the chai modules. That means (https://github.com/nodejs/LTS): 
 
 - Anything less than 0.12 is not supported by us
 - Node 0.12 should be supported until Dec 31st.
 - Node 4.x until April 2018
 - Node 5 gets no support from us
 - Node 6.x will be supported all the way to 2019, unless SkyNet happens of course

**Comment by lucasfcosta** [comment]
Well, then I'll send a PR for that on type-detect and stop testing on that environment.
I'll include only LTS versions on `.travis.yml`.

Let's just hope SkyNet does not happen until 2019 (unless it's written using Node).

**Comment by keithamus** [comment]
@amilajack has kindly done so for us here: https://github.com/chaijs/type-detect/pull/69. I think we can essentially crib from that PR, as it covers everything I've said here too. All of our travis builds should use that 😄

**Comment by lucasfcosta** [comment]
Ah, that's really awesome! I haven't seem that. Thanks for the link!
I will close this one as soon as that PR gets merged then.

**Comment by lucasfcosta** [comment]
So, it seems like chaijs/type-detect#69 is almost done!
The PR we needed is already merged in Travis.

So, should I copy the whole `.travis.yml` file from there to this project and submit a PR too?
I'm still not fully confortable with how these Sauce Labs keys work, I'll take a further look at it this week just to make sure I'll be doing the right thing.

**Comment by keithamus** [comment]
@lucasfcosta I need to regenerate tokens for pathval to use saucelabs - just ignore those tokens for now, I'll have a PR soon. Feel free to copy the rest of the `.travis.yml` though!

**Comment by lucasfcosta** [comment]
Okay, so I'm closing this since we've got the tokens and already fixed the failing build.
