### ISSUE TITLE
consider returning the target object from set

### ISSUE THREAD

**Issue by focusaurus** [chaijs/pathval#6]
I migrated from a similar module called lodash-deep. It had the nice feature that the `set` function would return the target object, so you could make a new object from a literal and assign it like this:

`var req = pathval.set({}, 'session.token.modelId', new ObjectID());`

In pathval, `req` ends up undefined here.

**Comment by keithamus** [comment]
@lucasfcosta think we should add this? Seems reasonable.

**Comment by lucasfcosta** [comment]
@keithamus seems reasonable to me too. Looks like a good idea.
I'll work on it as soon as I get some free time this weekend, it may be a pretty simple thing to do.
