### ISSUE TITLE
There is a fixable vulnerability inside

### ISSUE THREAD

**Issue by deleonio** [chaijs/pathval#61]
pathval inside @leanup/cli@1.0.46 › @leanup/cli-core-test@1.0.46 › chai@4.2.0 › pathval@1.1.0

 Vulnerability: https://snyk.io/test/npm/pathval/1.1.0

**Comment by martinoppitz** [comment]
Fixed by https://github.com/chaijs/pathval/pull/60

**Comment by SanthiSridharan** [comment]
Hello Maintainers - This is a quick and easy fix - Any interest in merging this - Appreciate your attention . Thank you @Deleonio

**Comment by MaxTerekhov** [comment]
+1

**Comment by christian-hawk** [comment]
+1

**Comment by darlanalves** [comment]
@deleonio  @keithamus we can close this issue, right? 

It was fixed by #60 in `1.1.1`

**Comment by keithamus** [comment]
Yep thanks for the reminder!
